ssbc/ssb-db

index.js, test/feed.js, test/history.js, test/linktypes.js, test/log.js, test/mesages-by-type.js, test/msg-encoding.js, test/validation.js
see https://github.com/ssbc/secure-scuttlebutt/issues/76
started by adding `keys: true` support to `createFeedStream`. waiting on the rest till we have agreement
=> standardizing getter output

README.md, index.js, package.json, test/linktypes.js, test/msg-encoding.js, test/rebuild.js, test/related-messages.js
https://github.com/ssbc/secure-scuttlebutt/issues/94
=> update to new link convention (bump ssb-msgs to 3.0.0, update tests)

test/feed.js, test/linktypes.js, test/log.js, test/mesages-by-type.js, test/msg-encoding.js, test/rebuild.js, test/related-messages.js, test/util.js
I merged https://github.com/ssbc/secure-scuttlebutt/pull/101 but forgot this.
=> fix tests for ssb-feed

index.js
use generic queries instead of hardcoded.
There is more work to do here, so won't be merging this just yet.
=> tracking pull request: mynosql

index.js, package.json
update pull-level to get [{sync: true}](https://github.com/dominictarr/pull-level#example-realtime-aggregation)
which will enable solving this https://github.com/dominictarr/level-memview/issues/1 easily
=> update pull-level to get sync option

test/validation.js, validation.js
per https://github.com/ssbc/secure-scuttlebutt/issues/110
=> increase msg size limit to 8kb

index.js, package.json, test/end-to-end.js, validation.js
@pfraze okay checkout the test to see what i'm doing for end-to-end,
first we have to pass the keys into secure-scuttlebutt (as third argument)
this is so that we can decrypt messages that need to be indexed.
Then, the client uses ssb-keys to decrypt the messages they want to view.
Maybe we can make that a bit better than the second part, but at least
by explicitly decrypting we can see who knows what.
=> first steps toward end to end

index.js, test/history.js
read a single user's stream in any range or order.
=> User stream

README.md
=> link to ssb-docs

index.js, test/linktypes.js, test/rebuild.js
we talked about this a while back,
needed to use this again for blocking.
=> Tracking: replace all the *Linked* functions with just one function.

create.js, index.js, test/end-to-end.js
also added a comment because I couldn't see where the decryption was when i reread the code.
=> more througher end-to-end tests

index.js, test/linktypes.js
sometimes you already know who may be linking to who, you just want to check whether they actually did.
this is needed in blocking in 2 instances (checking if A blocked B when B connects to A, or when B asks for A's feed)
=> fix edgecases when you know the source and the dest for a link

legacy.js
This PR attempts to count the total number of posts, and then once the count is complete, switches progress mode from **timestamp** to **total number**. Turns out it is much quicker to stream through the entire database if you aren't doing anything besides counting. The following code returns in under 10 seconds on my computer:
```js
var count = 0
var now = Date.now()
pull(
context.sbot.createLogStream(),
pull.drain(x => {
count += 1
}, () => {
console.log(count, (Date.now() - now) / 1000) // => 142596 9.368
})
)
```
That's at least 15 times quicker than the actual migration. It means that within 10 seconds a newly onboarded user will start seeing actual progress instead of more like 1.5 minutes (which is how long @mischa-saunders had to wait before the progress started to tick up on his …
=> migration: switch to count based progress once total known

legacy.js
=> oops, pass in the timestamp to the legacy migration

README.md
I tried the code from the README and hit a few problems, fixed here.
=> README example fixup

test/add.js
It seems like this was included in 18.0.1
=> reproduce @av8ta's issue #493

util.js
With this ssb-validate doesn't fail on the first message. It fails after around 1723 so there is still a bug in here somewhere.
=> Fix signature hash not working when reboxing

minimal.js, util.js
as that can be quite slow if the array is large
=> Don't use while + shift pattern 

minimal.js
Resolves #237 
This diff is just an indentation fix plus:
```diff
-msg.unbox = key.toString('base64')
+if (key) {
+  msg.unbox = key.toString('base64')
+}
```
I'm unclear on *how* this could be happening, but it seems that the following must be true to trigger this error:
- `isFunction(unbox) === false`
- `key == null`
- `unbox.key == null`
@dominictarr @ahdinosaur Is this fine, or should we throw an error if we can't set `msg.value.unbox`?
=> Key undefined

api.md, help.js, index.js
returns a datastructure describing all commands and options, for https://github.com/ssbc/ssb-server/pull/652
=> muxrpcli@3 style help

README.md
Based on @christianbundy's SSB comment here: %vaXZReDFCV09hnLGqgYxmacst8jboVM2kFwgMW4PK1s=.sha256
=> Add notes about decryption for different streams

help.js, index.js
Resolves #272 
We weren't actually exporting this so when experimenting with [ssb-cli](https://github.com/fraction/ssb-cli) there were lots of broken methods showing up.
=> Remove non-existed methods from muxrpc manifest

minimal.js
needed by private-groups,
so that previous is accessable, for instance. https://github.com/dominictarr/group-box needs an external nonce to decrypt (which is supplied as the previous hash)
=> also pass value to unboxValue

autobox.js, create.js, db.js, extras.js, index.js, indexes/keys.js, indexes/links.js, indexes/time.js, minimal.js, package-lock.json, package.json, test/rebuild.js, util.js
This PR:
- separates the setup requirements for reading / writing (unboxers / validators)
- fixes some bugs in how output of status / progress is caculates
:warning: needs new flumedb changes added
=> bugfix - rebuild

create.js
I was debugging something and was seeing an error in the neighbourhood of this method.
I got to logging and noticed some edge cases I could close
=> refactor db.get

README.md, autobox.js, index.js, package-lock.json, package.json, test/close.js, test/ghost.js, test/rebuild.js, test/unbox-with-cache.js, util.js
Problem: There's an issue where sometimes streams don't properly unbox
messages if you close the server and restart it, which is very
confusing. I've walked through the entire stack until I ended up here.
Solution: Add a test so that we can start putting together solutions to
this problem.
---
Problem: There's an issue where sometimes streams don't properly unbox
messages if you close the server and restart it, which is very
confusing. I've walked through the entire stack until I ended up here.
Solution: Add a test so that we can start putting together solutions to
this problem.
=> Fix ghost message bug from pass-by-reference
