test/validation.js, validation.js
https://github.com/ssbc/secure-scuttlebutt/issues/74
is there a better way to do this? would be great not to do a throwaway `JSON.stringify`
=> validation now rejects messages larger than 1024 bytes

README.md, index.js, test/related-messages.js
Basically the same as phoenix's `getThread`, except as a query instead of as a view/index.
It is simple to rebuild this on demand because we already have an index of links within messages, so it's just a few calls to get the "replies".
By passing in a `rel` type, you get only messages that reply by that type. Also supported are `count` and `parent` options, but they are off by default.
This can be used to implement comment threading, but also many other types of recursive structures based on message links.
I added api documentation, although I notice that the other documentation is kinda out of date.
=> relatedMessages

validation.js
We were experiencing long delays in the `feed.add()` function for reasons unknown (https://github.com/ssbc/phoenix/issues/299#issuecomment-73179046). Turns out it was because the validation pipeline was failing to resume processing after a message was rejected. Adding some `drain()` calls solved the issue.
Closes https://github.com/ssbc/phoenix/issues/299
=> fix: validation pipeline now drains after a validation error

index.js, package.json, test/history.js
this brings in some fixes through out pull-level and pull-paramap to make streams clean themselves up properly,
working towards memory leak problems. Since this adds onAbort to createHistoryStream it's a minor change.
=> make source streams abortable

index.js, test/end-to-end.js, test/linktypes.js, test/rebuild.js, test/related-messages.js, test/validation.js
I ended up changing how the link indexing works in this. All links create the same 3 indexes, now:
1. forward, from message author to link target
2. backward, from link target to message author
3. backward, from link target to message
This changes the `links()` function such that, if `type == msg`, then you'll get entries from index 3, and if `type == feed` then you'll get entries from index 1 and 2. `Type: msg` is now the default.
This change makes it possible to get links between feeds and messages/blobs.
However, this changes the meaning of the `type` parameter in `links()`. Instead of meaning, "give me links of that type," it's saying, "give me links *between* those types."
=> Update links and link-indexing to use sigils

index.js
`createLogStream` was previously ignoring everything but `gt`, `keys`, `values`, and `live`
=> fix: createLogStream now uses opts

index.js
I noticed that the gt/gte/lt/lte params were operating on the index without modification. Well, the feed index looks like `[ts, author]` so there's not much reason to query against that. This PR makes those params query against just `ts`
=> update createFeedStream range params to operate on timestaps

index.js, test/end-to-end.js, test/links.js, test/linktypes.js
After noticing that links was not handling some cases the other day, (in particular, queries where not filtered by rel at all) I rewrote links.
This bug was introduced by upgrading links to use sigils.
https://github.com/ssbc/secure-scuttlebutt/pull/125
This makes a breaking change: if a `source` (or source sigil) was not provided,
previously it defaults to the message as the source. but the author as the source makes more sense. You can get the message easily - from the `.key`
property (and have links return you the whole message with values: true)
Making source always be a feed is also more consistent with the query
input. It doesn't really make sense to query the source as a message
anyway.
This did mean changing the tests, but I grepped through patchwork and scuttlebot and we havn't …
=> rewrite links

index.js, package.json, test/history.js, test/latest.js
This changes a few apis as needed for replication back pressure.
This is a breaking change, but only changes a few small features.
* `latest` now returns tuples of `{sequence, ts}` instead of `sequence`. data created prior to this merge won't have ts, so it's left as `null` and replication can just handle that by allowing the maximum number of messages, and this will be updated as soon as one is received. `ts` is the local received time.
* `getLatest` is removed. This wasn't being used anymore.
and some feature additions
* `createHistoryStream` now accepts an integer `limit` property. incidentially, this means we can later add partial ranges and it won't be a breaking change.
Also, I added test coverage for `db.latest` and removed some dependencies which are no longer used.
=> apis needed for replication back pressure

index.md
This file is what will be used to create ssbc.github.io/secure-scuttlebutt. Generally I used each repo's README.md for the site, but for this one, I didn't. We can revisit the approach if unhappy with it.
=> add index.md

index.md
"entities" in this sentence confused me. Because an entity "is something that exists in itself". But feeds are composed of messages so they they are a single entity. "Objects" on the other hand is a more general term.
=> change entities to objects

index.js, test/related-messages.js
Prior to this PR, if you ran `relatedMessages()` on a msg-id that's not present†, but which does have present messages linking to the root, then `relatedMessages()` would call the cb() with an error message, and, in some cases, would call the cb *twice*, resulting in a backend crash (cb called twice error).
This PR does two things:
- Guards against the double cb-call
- Ignores a root-not-found error, so that the rest of the thread can be assembled
† present: saved in the local database
=> Ignore missing root message in relatedMessages()

index.js, package.json
mynosql was a cute idea, but streamviews are much better.
we never actually used mynosql features, so it's easy to remove it.
I think we can consider this a patch.
=> remove mynosql

index.js
After 
```
npm install ssb-patchwork -g
patchwork
```
Got the error
```
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).
Starting...
module.js:339
throw err;
^
Error: Cannot find module 'typewiselite'
at Function.Module._resolveFilename (module.js:337:15)
at Function.Module._load (module.js:287:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object.<anonymous> (/Users/glen/.nvm/versions/node/v4.2.2/lib/node_modules/ssb-patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:19:17)
at Module._compile (module.js:435:26)
at …
```
=> Fixed error "Cannot find module 'typewiselite'"

index.js, test/links.js
Turns out that #152 didn't fix what it was supposed to. The changed code wasn't covered by tests, so I didn't notice that the fix was not correct. The code path that uses `_value` is activated using `ssb.links({values: true, live: true, ...})`. Here I've corrected the fix and added a test to cover it.
=> Fix realtime links

package.json
This change adds NPM package that is used but not declared as dependency
to `dependencies` section of `package.json` file.
Patchwork fails to start without this change.
=> Add missing dependency to package.json file.

follower.js, index.js, util.js
`await` is a reserved word, and is disallowed by recent JavaScript parsers, such as Babylon. This has nothing to do with strict mode.
=> Replace await with wait

db.js, legacy.js, test/migration.js
this adds test coverage for migrations, and also the data we need for progress bars.
db. now has a `progress` object, which is a bunch of named items (so far, "migration" and "indexes") then in turn are 3-tuples of `{start: number, current: number, target: number}`
to get the current ratio for a progress bar use `Math.floor(current-start / target-start)` which gives a number that moves between 0 and 1. Obviously target should be greater than start, and it helps if start is also near the first value for current and it's extra nice if the current moves fairly evenly through the number space between start and target, but these things are only advisory. If current eventually ends up at current, we should get a half decent progress bar.
My intention is that other plugins that could make sense …
=> progress bar enabling api

legacy.js
I suppose this was a typo since there isn't `flume` defined anywhere else in this file. I actually found this as a runtime exception 
```
Log level: notice
RELOAD INDEX: {"version":13,"since":1497014424195}
RELOAD INDEX: undefined
LOAD LINKS SINCE null 0
/usr/src/app/node_modules/secure-scuttlebutt/legacy.js:98
prog = flume.progress.migration = {
^
ReferenceError: flume is not defined
at /usr/src/app/node_modules/secure-scuttlebutt/legacy.js:98:22
at /usr/src/app/node_modules/flumelog-offset/inject.js:66:14
at /usr/src/app/node_modules/flumelog-offset/frame/recoverable.js:40:11
at /usr/src/app/node_modules/aligned-block-file/blocks.js:69:11
at get (/usr/src/app/node_modules/aligned-block-file/blocks.js:25:7)
at next (/usr/src/app/node_modules/aligned-block-file/blocks.js:48:7)
at …
```
=> Fix typo in legacy.js

db.js
Currently when you try to use this inside an electron render process you get the following error:
```
TypeError: setInterval(...).unref is not a function
at module.exports (/Users/matt/Code/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/db.js:49:28)
at module.exports (/Users/matt/Code/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:51:27)
at module.exports (/Users/matt/Code/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/create.js:9:10)
at Object.init (/Users/matt/Code/patchwork/node_modules/scuttlebot/index.js:48:15)
at /Users/matt/Code/patchwork/node_modules/secret-stack/api.js:27:28
at Array.forEach (native)
at create (/Users/matt/Code/patchwork/node_modules/secret-stack/api.js:26:20)
at module.exports …
```
=> make work in electron, don't depend on node style setInterval(...).unref

package.json
=> Add missing dependency ltgt (used in indexes/last.js)

index.js
Right now if you call `get('someString')` things get really nasty. The request makes it all the way to https://github.com/flumedb/aligned-block-file/blob/master/blocks.js#L40 before throwing. It's also inside async so the stack trace is lost and you have no idea where the culprit is! (I wasted an hr trying to track down something thanks to this)
**This PR adds a check to ensure that the key is a number before passing it to flume. It throws an error if unhandled.**
_Warning: Code untested! Did this instead of an issue so the fix could be illustrated clearly. Not sure how to word the error message._
=> throw immediately when `db.get` called with a non-ref string

package.json
to bring in the fixes from flumedb/flumedb#7
(this is pre 1.0 so even with the `^`, it is fixed at 0.2.x)
@dominictarr
=> bump flumedb version

db.js, package.json, related.js, test/migration.js
replaces flumeview-level with a in memory hashtable! leveldb is slow in the browser, so this is a step towards that (still need to remove the flumeview-level for clock and backlinks)
=> use flumeview-hashtable

index.js
The `isFunction` function on line 34 in `index.js` is looking for type `funciton` rather than `function. This pull request fixes that error and correctly matches against type `function`. Closes #185
=> Fix `isFunction`

index.js
The createLogStream method in index.js is getting overwritten in extras.js, but I would like raw access to the method still, with range control, so I've renamed this one to a new method, so it is accessible.
=> Modify createLogStream in index.js to be createRawLogStream

indexes/last.js, test/latest.js
Running `sbot latest` on an idle and empty sbot server causes the server to crash.
```
$ ./bin.js server
Log level: notice
************************************************** (indexes:100%)/home/donp/code/scuttlebot/scuttlebot/node_modules/secure-scuttlebutt/indexes/last.js:33
cb(null, pull.values(Object.keys(val).map(function (author) {
^
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at /home/donp/code/scuttlebot/scuttlebot/node_modules/secure-scuttlebutt/indexes/last.js:33:39
at Object.get (/home/donp/code/scuttlebot/scuttlebot/node_modules/flumeview-reduce/inject.js:115:11)
at /home/donp/code/scuttlebot/scuttlebot/node_modules/secure-scuttlebutt/indexes/last.js:31:15
at /home/donp/code/scuttlebot/scuttlebot/node_modules/pull-cont/index.js:18:5
at …
```
=> .latest always returns an object

package-lock.json, package.json
This is the last package used in `scuttlebot` that still uses old `Leveldown@1.7.2`, crashing on mobile.
=> updated flumeview-level to latest

minimal.js
[This commit](https://github.com/ssbc/secure-scuttlebutt/commit/281ae35e755b44452bd5db395cd10ba0867756f4) moved unboxer out of the `codec`. This caused a crash in `addUnboxer` so fixed it.
=> BUGFIX: Crashing on `addUnboxer`

index.js, minimal.js, test/end-to-end.js, util.js
This change is an essential step in the long awaited private groups. it builds on quite a bit of work that has lead up to this, such as [passing decrypted messages to indexes](https://github.com/ssbc/secure-scuttlebutt/pull/199) and the api designed for [encrypted blobs](https://github.com/ssbc/ssb-ws/pull/9)
With this change, you decrypted private messages return an `unbox` key. This is the access code to that message. If someone has that key, they can decrypt that message! This is useful for private-groups because the point is to be able to add people to groups later. It is also a possibility that has always existed, since ssb uses on-the-record encryption. This ability _may_ be suprising for some people, which is why I want to be really explicit about it.
for example:
```
{
"key": …
```
=> pass a unbox key to a private message

README.md, minimal.js
I'm working toward using the flumedb map as a Scuttlebot plugin, but it seems like the first step would be to accept a function as `opts.map` that gets passed to flume. Is this the best way to go about that change?
Backlink: https://github.com/flumedb/flumedb/pull/19.
=> Add `addMap()` method

.gitignore
Been burned by this one too many times and I can't think of a reason not to add it.
=> Add `node_modules` to gitignore

.github/stale.yml
This adds a config for [Stale](https://github.com/apps/stale), which I'll enable for this repo if/when this PR is merged. I've used the default config, the only change being that I've replaced "wontfix" with "stale" and made a label for it. After 60 days the bot will comment, warning that the issue will soon be closed, and unless there's activity within 7 days the issue will close. I'm happy to change any of the config options, feel free to push to the branch.
=> Add config for Stale app

minimal.js
I was testing 05-ssb-legacy write to see where the time goes. Comparing with 01 validate I get validate: 53s, write + validate (05) 125s. Seems rather high for 42mb data. Looking around I found the async-write function that defaults to delay write 100 ms, but for some reason it set to 10ms in secure-scuttlebutt. Changing it to 100 ms makes a large difference. 15 seconds!
=> Wait 100ms before writing instead of 10ms

db.js, index.js, indexes/last.js, minimal.js
This reuses the id of ssb-validates append instead of recomputing it. On my machine this saves 5 seconds out of 157 seconds for benchmark 11 in bench-ssb.
=> Reuse hash of message instead of recomputing it

legacy.js, minimal.js
`ssb-server` doesn't even start for me (with current master branch)
```
/home/dominic/c/ssb-db/legacy.js:78
if (err) throw err
^
EncodingError: Unexpected token % in JSON at position 0
at /home/dominic/c/ssb-db/node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:60:28
at /home/dominic/c/ssb-db/node_modules/level/node_modules/abstract-leveldown/abstract-iterator.js:29:14
at /home/dominic/c/ssb-db/node_modules/level/node_modules/encoding-down/index.js:126:5
at /home/dominic/c/ssb-db/node_modules/level/node_modules/abstract-leveldown/abstract-iterator.js:29:14
at /home/dominic/c/ssb-db/node_modules/level/node_modules/leveldown/iterator.js:45:7
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
```
but …
=> explicitly ignore errors

README.md, create.js, test/add.js
it is kinda annoying that lots of things use a `{key,value,timestamp}` pattern but `sbot.get` doesn't do that.
this tends to mean that sometimes messages don't have received times... this adds a option to keep that.
`meta` is short for metadata. using this name is consistent with other uses for example `links` which uses takes a `meta` option (although that one defaults to true)
Making meta default to true here is probably a breaking change.
=> get ({id: id, meta: true}) to get {key,value,timestamp} format message

README.md, index.js
The documentation was previously _very bad_ this improves it significantly.
rate the current state of the documentation out of 10 - 2 (now much improved)
is it clear what this is used for? - needs more guidance around how to create ssb plugins, and setting up minimal ssb set ups.
is there api documentation? - Yes
read code, do you see any undocumented methods? - quite a few, but these are explicitly listed.
for a method is there any undocumented options? - probably, yes
=> documentation drive: document most important methods, list still undocumented methods, shift deprecated methods to deprecated section

README.md
this PR finishes documenting all the undocumented methods.
addUnboxer and unbox definitely need more work.
also, I noticed there are several methods (about getting the latest message) that do not seem to be in use anymore, they should probably be removed.
=> documentation drive: document what was undocumented

index.js, package.json
mdmanifest used to be widely used in ssb libraries, but not so much nowadays. ssb-db is the only one still using, as far as I know.
In codebases like Manyverse, we have to [patch the source code](https://github.com/staltz/manyverse/blob/3e6f756d8e67e19aefd7eb158718c4168bd893d5/tools/patch-backend-ssb-server#L29) of ssb-db to replace mdmanifest usage, because it does a `fs.readFileSync` on non-JavaScript files expected to be in node_modules, but those files are deleted because we run `noderify` and delete all other files, in order to drastically decrease the amount of bytes shipped to the user's app download or update.
Another justification for this is that mdmanifest doesn't help that much, but creates "two sources of truth" which need to be synchronized. JavaScript is not the single …
=> remove mdmanifest

index.js
Right now we aren't exporting a name, so it's hard to introspect which plugin this is without looking at the manifest.
=> Add secret-stack name for simpler debugging

README.md
there were fragmented references to the `sbot` instance, named as `sbot`, `feed`, and `ssb` ... rename them all to `sbot`. 
Also add backticks to module names, and fix API formatting
See here for the updated README not as raw markdown: https://github.com/ssbc/ssb-db/blob/729cb08a91e4b7f08cb7bfa1b7c193f14f51d76d/README.md
=> fix README example var references

index.js
Reverts #268 because it breaks ssb-db via muxrpc. I'm planning to add a backward-compat plugin as a sibling that exports everything with deprecation stack traces (except `createHistoryStream()`, of course).
=> Revert "Add secret-stack name for simpler debugging"

.travis.yml
Node 8 is almost at EOL, so I think it's probably fine to finally drop Node 6 support in favor of the active LTS.
=> Change Travis tests to replace Node 6 with Node 12

api.md, create.js, index.js, package.json, test/log.js
This is what we're doing manually in Patchwork, except for in Patchwork we're also keeping track of messages that are currently in the process of being deleted because it's common to call `del()` on the same message multiple times. I'm unsure whether we should:
- Add some code to support race conditions so `del()` can be called lots without errors.
- Leave as-is and probably have scenarios where `del()` called repeatedly throws errors.
Relevant Patchwork code: https://github.com/ssbc/patchwork/blob/a7dd2056bf17f0986cf3f8e4445fac3e024fb4ef/lib/main-window.js#L81-L121
=> Add support for deleting entire feed at once

package.json
Problem: The old version of FlumeDB can't auto-heal broken indexes.
Solution: Upgrade FlumeDB to ^2.1.1.
=> Upgrade FlumeDB

README.md, autobox.js, create.js, index.js, minimal.js, package.json, test/box-unbox.js, test/close.js, test/create-ssb.js, util.js
WIP:
:fire: This is a breaking change
I need to be able to do async lookups to look for appropriate keys for private-groups. 
This requires changing how boxers / unboxers work from sync > async.
---
what in the ecosystem is currently using these APIs `box` / `unbox`, `addBoxer` / `addUnboxer`?
if we're cutting a major release I intend to extract the box1 boxers/ unboxers so that they are optionally added as opposed to always on.
=> async boxers / unboxers

test/close.js
Problem: The `test/close.js` test was failing because the database
seems to have been empty, and since `createLogStream()` doesn't emit
items on an empty database then `pull.collect()` is never called. The
database is empty because the first test creates a database where `temp`
is implicitly true, which uses a directory like `/tmp/1590008707854`.
When the second test sets `temp` to false, it uses a named directory
like `/tmp/test-ssb-feed`, which is **empty**.
Solution: Pass `{ temp: false }` consistently to both tests.
=> Fix `test/close.js` on async-box with `{ temp }`

test/box-unbox.js
Problem: Now that boxers are optional, I'm worried that a future
programming mistake might see a message with `recps` properties that
doesn't get boxed because no boxer is available.
Solution: Add a test to ensure that this does not currently happen and
cannot happen in the future.
---
Test fails because of #290
=> Add test for unbox failing without unboxer

.travis.yml, package.json, test/add.js, test/append.js, test/box-unbox.js, test/close.js, test/feed.js, test/history.js, test/latest.js, test/links.js, test/linktypes.js, test/log.js, test/manifest.js, test/mesages-by-type.js, test/msg-encoding.js, test/rebuild.js, test/util/create-ssb.js, test/validation.js, test/write-stream.js
This PR changes:
1. the travis config:
- adds Mac + Windows
- the general config (:warning: I've just changed it, don't know what the implications are)
2. hows the tests are run
- moved to using tape as a runner so windows can run
- this has necessitated a refactor of the tests files
I've checked the number of tests before / after and ensured that 265 tests are still being run
=> travis: add mac+win

autobox.js, minimal.js, package.json, test/box-unbox.js
```
/* NOTE
* currently when flumedb passes messages to each view (index) it runs
* an unbox on encrypted messaged FOR EVERY VIEW
*
* This is a temporary easy solution to reduce some wasted CPU cycles
* without having to change deep things about flumedb
*/
```
This PR uses an LRU style cache to _bound_ the amount of the memory this unbox cache will use.
This needs to take into account index rebuilds in the context where you've just been given a private group key. This is why there's (untested) code which closes over the `flume.rebuild` function
=> put an LRU cache over unbox

package-lock.json, package.json
there was some security warning about minimist which mkdirp depends on.
noticed there was a major version with a simialr API (for our purposes, so bumped)
=> upgrade mkdirp

package.json
was doing some work the other day and upgraded the dependency for one reason or another.
It generated new failing tests ... specifically I _think_ it might be catching tests which are run _after `t.end()` has been called_ . 
This seems like a useful thing to look into more at some point
=> WIP upgrade to tape@5

autobox.js, create.js, test/unbox-with-cache.js
Problem: HashLRU passes references, not values, so when we use the cache
we're accidentally creating a scenario where one variable being mutated
can change the contents of the results of another query.
Solution: Use `lodash.cloneDeep()` on the results from the HashLRU cache
to ensure that we're always passing by value rather than by reference.
---
I was going to make an issue for this, but I figured I should just fix it instead. I think this is better than `Object.freeze()` because that makes you *think* that you can change an object (no errors) but quietly drops any changes that you try to make.
=> Fix pass-by-reference from cache

index.js
Problem: For some reason the Travis CI Windows builds fail
intermittently with a specific error that doesn't make any sense to me.
We've been just restarting the build, since the erorr (can't close the
server because the server is already closed) doesn't matter, but it's
still very obnoxious.
Solution: Ignore the error entirely and don't worry about it. I don't
think that we care if the server is already closed, the important thing
is that it's closed. I'm okay with `close()` being idempotent.
Resolves: #300
=> Fix intermittent Windows test failures

README.md, autobox.js, index.js, minimal.js, test/append.js, test/get-feed-state.js
Alternative to #311 which automatically passes feed state to the boxer, exposing a method instead of an observable for further use.
---
Problem: Some boxers, like SSB-Tribe, depend on the feed state. We've
tried using hacks to query the database before publishing a message, but
we really just need to be passed the feed state (according to the
validator) each time the boxer is asked to box a message.
Solution: Pass the relevant feed state from the validator to the boxer.
There are also some circumstances where we want some specific feed
state, like when boxing a message to pass to `add()` rather than
`append()`, and so I've added a `getFeedState()` method that returns
those results.
=> Pass feed state to boxer

README.md
I discovered in testing `ssb-tribes` that `opts.seq` did not behave as the docs describe - there was an "out by one" error.
`createHistoryStream` is defined in `indexes/clock.js` : 
```js
index.createHistoryStream = function (streamOpts) {
const opts = u.options(streamOpts)
var id = opts.id
var seq = opts.sequence || opts.seq || 0
var limit = opts.limit
var keys = opts.keys
var values = opts.values
return pull(
index.read({
gte: [id, seq],                  // <<<<<<<<< greater than OR EQUAL TO
lte: [id, MAX_INT],
live: opts && opts.live,
old: opts && opts.old,
keys: false,
sync: (opts && opts.sync) === false,
limit: limit
}),
// NEVER allow private messages over history stream.
// createHistoryStream is used for legacy replication.
u.Format(keys, values, false)
)
}
```
this adjusts the …
=> update createHistoryStream opts.seq documentation

README.md
Add a note to the readme about `ssb-server` vs `secret-stack`. Related to issue [314](https://github.com/ssbc/ssb-db/issues/314)
=> clarify `ssb-server` use

README.md, create.js, test/add.js
Context: https://github.com/ssb-ngi-pointer/ssb-db2/pull/97
Problem: in ssb-db2 we need to efficiently perform migration from log.offset to log.bipf, and for that we need to retrieve the *offset on log.offset of the latest migrated record*, because our process works like this: (1) pick the last record in log.bipf, (2) pick its `msg.key`, (3) retrieve the record on log.offset that matches `msg.key`, (4) retrieve the offset of that record on log.offset, (5) continue scanning log.offset from that specific offset.
Solution: to perform steps (4) and (5), we need `get(msgkey, cb)` to give us also the offset. This PR returns the offset as the 3rd CB argument. Why the 3rd arg? Because it's backwards compatible with whatever ssb-db was doing and providing to other parts of the stack (i.e. we don't …
=> db.get to return flumedb offset in the 3rd arg

README.md
README was missing documentation for `db.rebuild()`.
=> Add rebuild documentation
